# vim: set filetype=python :
import os,sys

Import('env')

name="total_int"
dlm=name+".dlm"
env.SharedLibrary(target="../DLM/"+name, source=name+".c",
                  SHLIBPREFIX='')
env.Command("../DLM/"+dlm,dlm,Copy("$TARGET","$SOURCE"))
