# vim: set filetype=python :
import os

Import('env')

env.SharedLibrary(target="../DLM/total_int", source="total_int.c",
                  SHLIBPREFIX='')
env.Command("../DLM/total_int.dlm","total_int.dlm",Copy("$TARGET","$SOURCE"))
